# Generated by Django 4.0.3 on 2022-04-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.CharField(max_length=15)),
                ('runtime', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('minutes_seen', models.IntegerField()),
                ('is_fully_seen', models.BooleanField(default=False)),
            ],
        ),
    ]
